### ISSUE TITLE
getPoolsPricesPairs error - unknown pool type

### ISSUE THREAD

**Issue by stephaneHerraiz** [cosmology-tech/cosmology#25]
Whe I run the getPoolsPricesPairs function :
```
this.client = await osmosis.ClientFactory.createRPCQueryClient({ rpcEndpoint: 'https://rpc.osmosis.zone'});
const {
    pools,
    prices,
    pairs
} = await getPoolsPricesPairs(this.client);
```
I receive this error :
Uncaught Error Error: unknown pool type
    at <anonymous> (/home/herraiz/dev/cosmos-osmosis-fetcher/node_modules/@cosmology/core/main/utils/osmo/pools.js:87:25)
    at _callee$ (/home/herraiz/dev/cosmos-osmosis-fetcher/node_modules/@cosmology/core/main/utils/osmo/pools.js:76:39)
    at tryCatch (/home/herraiz/dev/cosmos-osmosis-fetcher/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
    at <anonymous> (/home/herraiz/dev/cosmos-osmosis-fetcher/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
    at <anonymous> (/home/herraiz/dev/cosmos-osmosis-fetcher/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (/home/herraiz/dev/cosmos-osmosis-fetcher/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/herraiz/dev/cosmos-osmosis-fetcher/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
    at processTicksAndRejections (internal/process/task_queues:95:5)

**Comment by Steven-Chang** [comment]
me too

**Comment by Steven-Chang** [comment]
@stephaneHerraiz - This has got to do with:

https://github.com/osmosis-labs/osmojs/issues/5

If you look at error log and the file and line
`at (/home/herraiz/dev/cosmos-osmosis-fetcher/node_modules/@cosmology/core/main/utils/osmo/pools.js:87:25)
`
You'll see that the error is throw when there is no data.$typeUrl - You could fork and modify the files as required or we'll have to wait for cosmology-tech to update.

**Comment by pyramation** [comment]
which versions are you both running? This should be solved in the latest.

**Comment by pyramation** [comment]
should be fixed!
